# Generated by Django 4.0 on 2022-02-13 13:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ('fechaCreacion',)},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagenPublicacion',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='nombCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.categorias'),
        ),
    ]
