# Generated by Django 4.0 on 2022-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_publicacion_options_publicacion_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
