# Generated by Django 4.0 on 2022-02-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_alter_publicacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='nombAutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.autores'),
        ),
    ]
